version: "3.9"

services:
  app:
    build: .
    container_name: chatterbox-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/chatterbox?sslmode=disable
    depends_on:
      - db
    networks:
      - chatterbox-network

  db:
    image: postgres:13
    container_name: chatterbox-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatterbox
    volumes:
      - chatterbox-db-data:/var/lib/postgresql/data
    networks:
      - chatterbox-network

networks:
  chatterbox-network:
    driver: bridge

volumes:
  chatterbox-db-data:
